### ISSUE TITLE
administration/JSONEditor/About - HTTP Status 500 – Internal Server Error

### ISSUE THREAD

**Issue by ukrishne** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.json-editor#16]
### Current Behavior

Dear Team,

Thanks for your efforts.
 as per below image about page is not working "administration/JSONEditor/About - HTTP Status 500 – Internal Server Error"
![image](https://github.com/user-attachments/assets/e82e3351-1dbb-4b3b-b6ef-6d2fa0dff94b)

file is missing: "/webapp/json-editor-admin/html/about.html"

### Expected Behavior

about page should work

### Steps To Reproduce

please check the screenshot

### Environment - OS

Windows

### Polarion version

2404

### Extension Version

https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.json-editor/releases/tag/v1.6.0

**Comment by grigoriev** [comment]
Hi, should be already fixed in v1.7.0: https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.json-editor/releases/tag/v1.7.0
Could you please check again?

**Comment by ukrishne** [comment]
Dear Sergey,
It has been fixed in Bundle-Version 1.7.0.
When i tried yesterday there was no tag created, today with the latest tag i have tested. it worked. thanks for your advise.

Best Regards
Umesha Krishnegowda
